spring.application.name=KaplatC
server.port=8496



spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# URL Structure: jdbc:postgresql://<HOST>:<PORT>/<DB_NAME>
spring.datasource.url=jdbc:postgresql://localhost:5432/operations

# User name
spring.datasource.username=postgres

# Password
spring.datasource.password=docker

# Driver (Optional but good to have)
spring.datasource.driver-class-name=org.postgresql.Driver

# --- MongoDB Configuration ---
# Format: mongodb://<host>:<port>/<database_name>
spring.data.mongodb.uri=mongodb://mongo-db:27017/calculator